#!/bin/sh
echo "Removing Aglare-FHD-CBL..."
rm -rf /usr/share/enigma2/Aglare-FHD-CBL  > /dev/null 2>&1
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/Aglare  > /dev/null 2>&1
rm -r /usr/lib/enigma2/python/Components/Aglare* > /dev/null 2>&1
rm -r /usr/lib/enigma2/python/Components/Converter/Aglare* > /dev/null 2>&1
rm -r /usr/lib/enigma2/python/Components/Renderer/Aglare* > /dev/null 2>&1
rm -r /usr/lib/enigma2/python/Components/Converter/MSNWeather.py > /dev/null 2>&1
rm -r /usr/lib/enigma2/python/Components/Renderer/MSNWeatherPixmap.py > /dev/null 2>&1
rm -r /usr/lib/enigma2/python/Components/Sources/MSNWeather.py /dev/null 2>&1
rm -r /usr/lib/enigma2/python/Components/WeatherMSN.py /dev/null 2>&1
rm -rf /usr/lib/enigma2/python/Plugins/SystemPlugins/WeatherComponentHandler > /dev/null 2>&1
rm -rf /usr/lib/enigma2/python/Plugins/SkinComponents/WeatherComponent > /dev/null 2>&1
rm -rf /usr/lib/enigma2/python/Plugins/Extensions/WeatherPlugin > /dev/null 2>&1
sleep 2
echo "                                                          "
echo "Aglare-FHD-CBL was removed successfully."
echo "                                                    "
sleep 2
exit 0
