#!/bin/sh

if [ -d /control ] ; then
rm -rf /control  > /dev/null 2>&1
fi
sleep 2
if [ -d /CONTROL ] ; then
rm -rf /CONTROL  > /dev/null 2>&1
fi
sleep 2
if [ -f /control ] ; then
rm -rf /control  > /dev/null 2>&1
fi
exit 0
